name: R Script

on:
#  schedule:
#    - cron: "0 0 * * *"
  push:
    branches:
      - main

permissions : 
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: "4.2.2"
    
    - name: Check the dependency cache
      id: check-cache
      uses: actions/cache@v2
      with:
        path: ${{ runner.home }}/R/Library
        key: ${{runner.os}}-r-packages-$

    - if: ${{ steps.check-cache.outputs.cache-hit != 'true' }}
      name: Install dependencies
      run: |
        sudo apt install build-essential gfortran
        sudo apt-get install libcurl4-openssl-dev r-base
        R -q -e "install.packages(c('curl'))"
        Rscript -e 'install.packages(c("curl", "TTR", "quadprog", "httr", "quantmod", "timeDate", "plyr", "mfGARCH", "rugarch"))'
        Rscript -e 'install.packages(c("tseries", "dplyr", "tidyr", "zoo", "lubridate", "readr", "ggplot2", "alfred"))'

    - name: Execute R script
      run: Rscript daily_routine.R

    - name : Commit files
      env :
        AUTH : ${{ secrets.GITHUB_TOKEN }}
      run : |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action - HOUST"

        git remote rm origin
        git remote add origin https://${AUTH}@github.com/louisgeist/Real_time_volatility_prediction.git
        git pull origin main
        git add --all
        git commit -m "daily data import"

    - name : Push changes
      run : |
        git push --quiet --set-upstream origin HEAD:main
        echo "pushed to github"